### PR TITLE
Ignore `:through` associations in `IncorrectDependentOption` detector

### LINKED ISSUE #123: undefined method `class_name' for nil:NilClass
Hi,
I'm not sure why, and it may be a specific bug in my repository, but I am getting this error:
```
NoMethodError: undefined method `class_name' for nil:NilClass
Did you mean?  class_eval
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/reflection.rb:1021:in `derive_class_name'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/reflection.rb:166:in `class_name'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/reflection.rb:793:in `klass'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:58:in `block (2 levels) in detect'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:51:in `each'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:51:in `block in detect'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:44:in `each'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:44:in `detect'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/base.rb:50:in `run'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/base.rb:17:in `run'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:15:in `block in run_one'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/errors.rb:5:in `handle_exception'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:14:in `run_one'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:26:in `block in run_all'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:25:in `each'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:25:in `run_all'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/rake/task.rb:60:in `block in define'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:25:in `load'
/usr/local/bundle/bin/rake:25:in `<main>'
Tasks: TOP => active_record_doctor
```

The truth is that I don't have much of an idea how to start solving it.
Thank you very much

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #123.

### CODE REVIEW

**Comment by ocarreterom** [comment]
This fix works for me.

**Review by gregnavis — APPROVED** [review]

**Review by gregnavis — CHANGES_REQUESTED** [review]
I do have some feedback here. Will post later.

**Comment by gregnavis** [comment]
@ocarreterom, please check whether `master` works for you. It seems the error is caused by the lack of `has_many` on the middle association. For example, the following snippet would trigger the error:

```ruby
class User < ApplicationRecord
  has_many :posts
  has_many :comments, through: :posts
end

class Post < ApplicationRecord
  belongs_to :user
  # If the association below is missing then the error you reported will be raised.
  # has_many :comments
end

class Comment < ApplicationRecord
  belongs_to :post
end
```

---

@fatkodima, I'm closing the PR in favor of https://github.com/gregnavis/active_record_doctor/commit/def30ee5353e5877ac08d0150bac2b0d943d22df. The rationale is that it's entirely valid to use `dependent:` and `through:` on the same association, so skipping them would introduce a bug into the linter and gloss over the cases the detector is supposed to detect.

The fixed I push instead adds support for `through:` associations as well as detection of `nil` in `source_location`.

**Comment by fatkodima** [comment]
Yeah, sure, thanks! I overlooked that 🤦

**Comment by ocarreterom** [comment]
@gregnavis now I get this error:
```
NoMethodError: undefined method `klass' for nil:NilClass
    association_on_join_model = through_association.klass.reflect_on_association(association.name)
                                                    ^^^^^^
```

Is it expected?

**Comment by gregnavis** [comment]
@ocarreterom, a bit unexpected. If `through_association` is `nil` then your model may look like this:

```ruby
class User < ApplicationRecord
  has_many :comments, through: :posts

  # There's no `posts` association even though it's used in through.
end
```

I may need to add some debugging capabilities to `active_record_doctor` to make it easier to discover which model it's failing on. I'll push something later today.

**Comment by ocarreterom** [comment]
@gregnavis thanks!
Yes, if the error logs the file that is failing, it would be a good help since my project has >100 models 😕

**Comment by gregnavis** [comment]
@ocarreterom, I added debug logging in https://github.com/gregnavis/active_record_doctor/commit/9210a46b4cdebb649bfa3e134af598b52b5aa5c7. Could you give that commit a try? You can enable debug logging via:

```
ACTIVE_RECORD_DOCTOR_DEBUG=true bundle exec rails active_record_doctor:incorrect_dependent_option
```

Basically, whenever `ACTIVE_RECORD_DOCTOR_DEBUG` is defined (no matter the value) it'll enable debug logging in *any detector*.

**Comment by ocarreterom** [comment]
@gregnavis , maybe the error comes from `has_and_belongs_to_many` association.

```
has_many :professional_schedules
  through association with nil source_reflection

NoMethodError: undefined method `klass' for nil:NilClass
  association_on_join_model = through_association.klass.reflect_on_association(association.name)
                                                 ^^^^^^
```

```rb
has_many :professional_time_tables_professionals # a `has_and_belongs_to_many` table
has_many :professional_schedules, through: :professional_time_tables_professionals # This line fails
```

The model `models/professional_time_tables_professional.rb` exists.

**Comment by ocarreterom** [comment]
@gregnavis , I found the error.
I had `has_and_belongs_to_many :professional_time_tables`, where `professional_time_tables` its not a "has to many" table.

I don't know if the debug mode could be improved to log this kind of errors, at least this gem was useful to find an error in my code 😄

Thanks for all your help.

**Comment by gregnavis** [comment]
Fantastic, @ocarreterom! Squashing bugs is exactly what `active_record_doctor` is for, though this case was more complex than most 😄 

I'm not completely sure without seeing the code, but you may want to change how you implemented that many-to-many associations. Let's say that developers can be assigned to projects in a many-to-many fashion. There are two options:

1. If the assignment doesn't need to be manipulated as a separate model then you can use `has_and_belongs_to_many` on `Developer` and `Project`.
2. If the assignment has to be manipulated as a separate model then you should use `has_many`, `has_many through:` and `belongs_to`.

Code speaks louder than words so here's an example:

```ruby
# Option 1: has_and_belongs_to_many
class Developer < ApplicationRecord
  has_and_belongs_to_many :projects
end

# Assignment is NOT a separate model, but there's a developers_projects join table.

class Project < ApplicationRecord
  has_and_belongs_to_many :developers
end

# Option 2: has_many, has_many through:, belongs_to
class Developer < ApplicationRecord
  has_many :assignments
  has_many :projects, through: :assignments
end

class Assignment < ApplicationRecord
  belongs_to :developer
  belongs_to :project
end

class Project < ApplicationRecord
  has_many :assignments
  has_many :developers, through: :assignments
end
```

You may also want to revisit [the relevant sections in The Rails Guides](https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many). API docs for [`has_and_belongs_to_many`](https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many) say:

> The join table should not have a primary key or a model associated with it

**Pull request closed without merging**
